---
- name: Power off ESXi hosts
  hosts: localhost
  connection: local
  collections:
  - community.general
  - community.hashi_vault
  vars:
    ansible_hashi_vault_url: "https://vault.service.consul:8200"
    ansible_hashi_vault_validate_certs: false
    ansible_hashi_vault_token: ""
    vcenterhostname:    ""
    vcenterusername:    ""
    vcenterpassword:    ""
    esxi_ip:
        - "<IP_EXSI>"
        - "<IP_ESXI>"
    telegram:
         token:   "<token>"
         chat_id: "<id>"

  tasks:
  - name: Install python packages
    ansible.builtin.pip:
      name:
      - hvac
      - pyvmomi==8.0.2
      executable: pip3

  - name: Set the state of a host system to power down to standby
    vmware_host_powerstate:
      hostname: "{{ vcenterhostname | default(lookup('hashi_vault', '<path>/esxi:vcenterhostname'), true) }}"
      username: "{{ vcenterusername | default(lookup('hashi_vault', '<path>/esxi:vcenterusername'), true) }}"
      password: "{{ vcenterpassword | default(lookup('hashi_vault', '<path>/esxi:vcenterpassword'), true) }}"
      validate_certs: no
      esxi_hostname: "{{ item }}"
      state: shutdown-host
      force: true
    delegate_to: localhost
    failed_when: false
    register: task_power_off
    loop: "{{ esxi_ip }}"

  - name: Send notify to Telegram
    telegram:
      token: '{{ telegram.token }}'
      api_args:
        chat_id: "{{ telegram.chat_id }}"
        parse_mode: "markdown"
        text: "Send power off {{ item.item }}"
        disable_web_page_preview: true
        disable_notification: true
    loop: "{{ task_power_off.results }}"
    failed_when: false




