---
- name: Power on hosts
  hosts: localhost
  connection: local
  gather_facts: true
  force_handlers: true
  ignore_unreachable: true
  collections:
  - community.general.ipmi_power
  - community.hashi_vault
  - dellemc.openmanage.redfish_powerstate
  - community.general
  vars:
    ansible_hashi_vault_url: "https://vault.service.consul:8200"
    ansible_hashi_vault_validate_certs: false
    ansible_hashi_vault_token: ""
    ipmi_host:
        - "<IP>"
        - "<IP>"
    idrac_host:
        - "<IP>"
        - "<IP>"
    telegram:
         token:   ""
         chat_id: ""

  tasks:
  - name: Initialize log
    set_fact:
      execution_log: []
    delegate_to: localhost

  - name: Install python packages
    ansible.builtin.pip:
      name:
      - hvac
      - pyghmi
      executable: pip3

  - name: Ensure reports directory exists
    file:
      path: ./reports
      state: directory
    delegate_to: localhost
    run_once: true

  - name: Loop with logical
    include_tasks: task_power_on.yml
    loop: "{{ (ipmi_host | default([], true) + idrac_host | default([], true)) | flatten }}"

  - name: Generate Report
    template:
        src: report.j2
        dest: "./reports/report_{{ ansible_play_name }}_{{ lookup('pipe', 'date +%Y%m%d_%H%M%S') }}.txt"
    delegate_to: localhost
    run_once: true

  handlers:
  - name: "Send notify on Telegram"
    telegram:
      token: '{{ telegram.token }}'
      api_args:
        chat_id: "{{ telegram.chat_id }}"
        parse_mode: "markdown"
        text: "{{ tg_msg }}"
        disable_web_page_preview: true
        disable_notification: false